---
# Koyeb deployment configuration for WealthFam
# This enables one-click deployment to Koyeb

services:
  - name: wealthfam
    git:
      repository: github.com/oksbwn/wealthfam
      branch: main
    docker:
      dockerfile: Dockerfile
    env:
      - name: DATABASE_URL
        value: "duckdb:////data/family_finance_v3.duckdb"
      - name: VITE_APP_BUILD
        value: "koyeb-latest"
    ports:
      - port: 80
        protocol: http
    regions:
      - fra
    instance_type: nano
    scaling:
      min: 1
      max: 1
    health_checks:
      http:
        path: /health
        port: 80
    volumes:
      - path: /data
        size: 1GB
